net:
    arch: resnet18
    dataset: CIFAR10
    lr: 0.1
    pretrained: 1
    train_epochs: 100
    train_per_epoch: 2
    warmup: 10
    batch_size: 64
    weight_decay: 0.0005

control:
    turn: 1
    iteration: 1 2 3 4
    epoch: 1
    layer: 1 2 3 4 5 6 
    type: 1

exper:
    imp_total_iter: 5
    num_trial: 3
    acc_thrd: 80
    type: performance
    prune_perc_per_layer: 0.10
    gpu_id: 0
